pipeline {
  agent any
  stages {

    stage('Deploy') {
      steps {
        sshagent(['ec2-ssh-key']) {
          sh """
            ssh -o StrictHostKeyChecking=no ec2-user@${EC2_IP} "
              sudo systemctl stop apache2
              cd /var/app
              sudo git pull origin ${Tasketos_BRANCH}
              sudo systemctl start apache2
            "
          """
        }
      }
    }
  }
}