pipeline {
  agent any
  options { skipDefaultCheckout() }
  stages {

    stage('Deploy') {
      steps {
        sshagent(['ec2-ssh-key']) {
          sh """
            echo ${EC2_IP} 
            echo ${Tasketos_BRANCH}
            ssh -o StrictHostKeyChecking=no ${EC2_IP} "
              sudo systemctl stop apache2
              cd /var/www/html
              sudo git pull ${Tasketos_BRANCH}
              sudo systemctl start apache2
            "
          """
        }
      }
    }
  }
}