pipeline {
  agent any
  options { skipDefaultCheckout() }

  environment {
        othersKey = credentials('othersKey')
    }
  stages {

    stage('Deploy') {
      steps {
        
          sh """
            echo ${EC2_IP} 
            echo ${Tasketos_BRANCH}
            ssh -o StrictHostKeyChecking=no -v  -i ${othersKey} ${EC2_IP}"
              sudo systemctl stop apache2
              cd /var/www/html
              sudo git pull ${Tasketos_BRANCH}
              sudo systemctl start apache2
            "
          """
        
      }
    }
  }
}